services:
  rtsp_detect:
    build: .
    user: 1000:1000
    restart: unless-stopped
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 5000:5000
    command:
      [
        "python3",
        "rtsp_detect_people.py",
        "--config", "config.json",
        "--save",
        "--email",
        "--detect",
        "--web", "5000"
      ]
